$(document).ready(function(){
 $("#aboutme").click(function(){
  $("h1").fadeOut();
   $("#portfolio").fadeOut();
    $("#projects").fadeOut();
     $("#aboutme").fadeOut();
      $("#info").fadeIn(2000);
      $("#back").show();
       $("div").animate({height:'150px'},2000);
       
  });
  $("#back").click(function(){
   $("h1").fadeIn(2000);
    $("#portfolio").fadeIn();
     $("#projects").fadeIn();
      $("#aboutme").fadeIn();
      $("div").animate({height:'3px'});
       $("#back").hide();
         $("#info").hide();
  });
});